¿What has been the been the influence of the COVID19 in the polution levels of one of the main capitals in Europe?

- Superposed plots showing icreased or decreased values    
- Correlation matrices
- Heatmap showing the zones of more intense trafic

In [1]:
import pandas as pd
import numpy as np

In [8]:
df_polution = pd.read_csv('data\\datos202002.csv', sep=';')
df_polution.head()

,PROVINCIA,MUNICIPIO,ESTACION,MAGNITUD,PUNTO_MUESTREO,ANO,MES,D01,V01,D02,...,D27,V27,D28,V28,D29,V29,D30,V30,D31,V31
0,28,79,4,1,28079004_1_38,2020,1,9.0,V,10.0,...,0.0,N,0.0,N,0.0,N,6.0,N,7.0,V
1,28,79,4,1,28079004_1_38,2020,2,8.0,V,9.0,...,9.0,V,11.0,V,1.0,N,0.0,N,0.0,N
2,28,79,4,6,28079004_6_48,2020,1,0.7,V,0.7,...,0.0,N,0.0,N,0.0,N,0.1,N,0.1,V
3,28,79,4,6,28079004_6_48,2020,2,0.1,V,0.1,...,0.1,V,0.2,V,0.6,N,0.0,N,0.0,N
4,28,79,4,7,28079004_7_8,2020,1,80.0,V,116.0,...,0.0,N,0.0,N,0.0,N,5.0,N,7.0,V

PROVINCIA -> PROVINCE
MUNICIPIO -> MUNICIPALITY
ESTACIÓN -> STATION
MAGNITUD TÉCNICA -> TECHNICAL MAGNITUDE
PUNTO_MUESTREO -> STATION_ID
ANO -> YEAR
MES -> MONTH
DÍA -> DAY
PERIODO -> TIME PERIOD
ANÁLISIS -> ANALISYS


DATO -> DATA VALUE
CÓDIGO DE VALIDACIÓN -> CODE OF VALIDATION

In [14]:
df_polution.groupby(['ESTACION', 'MAGNITUD']).sum()[0:10]

                   PROVINCIA  MUNICIPIO   ANO  MES    D01    D02    D03  \
ESTACION MAGNITUD
4        1                56        158  4040    3   17.0   19.0   19.0
         6                56        158  4040    3    0.8    0.8    1.1
         7                56        158  4040    3   83.0  123.0  176.0
         8                56        158  4040    3   71.0   96.0  112.0
         12               56        158  4040    3  199.0  285.0  382.0
8        1                56        158  4040    3   14.0   14.0   15.0
         6                56        158  4040    3    1.0    0.9    1.4
         7                56        158  4040    3   70.0   74.0  187.0
         8                56        158  4040    3   95.0  100.0  124.0
         9                56        158  4040    3   35.0   28.0   59.0

                     D04    D05    D06  ...    D22    D23    D24    D25   D26  \
ESTACION MAGNITUD                       ...
4        1          18.0   17.0   18.0  ...   11.0   11.0   11.0   12.0  10.0
         6           0.8    0.8    0.9  ...    0.4    0.3    0.4    0.3   0.1
         7         112.0   86.0  108.0  ...   42.0   28.0   47.0   53.0  10.0
         8          82.0   99.0  106.0  ...   59.0   48.0   59.0   43.0  25.0
         12        253.0  230.0  272.0  ...  122.0   90.0  131.0  124.0  41.0
8        1          16.0   16.0   15.0  ...   16.0   15.0   14.0   14.0  13.0
         6           1.0    0.8    1.1  ...    1.0    0.9    0.9    0.8   0.7
         7          95.0   47.0   72.0  ...   55.0   42.0   49.0   64.0  18.0
         8         103.0  106.0  120.0  ...  122.0  105.0  116.0  102.0  77.0
         9          30.0   14.0   27.0  ...   21.0   26.0   23.0   20.0  13.0

                    D27   D28    D29   D30   D31
ESTACION MAGNITUD
4        1          9.0  11.0    1.0   6.0   7.0
         6          0.1   0.2    0.6   0.1   0.1
         7          8.0  32.0   61.0   5.0   7.0
         8         25.0  42.0   60.0  21.0  20.0
         12        38.0  90.0  153.0  29.0  30.0
8        1         13.0  14.0   13.0   6.0   6.0
         6          0.8   0.8    0.7   0.4   0.4
         7         38.0  51.0   34.0  16.0  15.0
         8         92.0  97.0   72.0  41.0  38.0
         9         27.0  25.0   19.0   6.0   5.0

[10 rows x 35 columns]